### ISSUE TITLE
GPLv3 code is included in this project

### ISSUE THREAD

**Issue by mementum** [quantrocket-llc/codeload-demo#1]
The backtrader quickstart code examples are covered by the GPLv3 license.

This licence is **NOT** included in the modified files.

Furthermore the Apache Software Foundation indicates that you CANNOT do it:

  - https://www.apache.org/legal/resolved.html#category-x

Be so kind to remove any traces of derivative works of the backtrader quickstart guide

**Comment by brian-from-quantrocket** [comment]
Arguably, redistributing a usage example is covered by fair use (https://www.gnu.org/licenses/gpl-faq.en.html#GPLFairUse). However, since fair use can be nebulous, I'll be happy to replace the quickstart example with a different backtrader example. No problem.

**Comment by brian-from-quantrocket** [comment]
The modified quickstart demos have been replaced with an original demo.
